# Generated by Django 2.1.1 on 2019-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=40)),
                ('eemail', models.CharField(max_length=40)),
                ('eusername', models.CharField(max_length=40)),
                ('epassword', models.CharField(max_length=40)),
                ('econtact', models.CharField(max_length=40)),
                ('epic_path', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
