# Generated by Django 2.1.1 on 2019-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=40)),
                ('semail', models.CharField(max_length=40)),
                ('scontact', models.CharField(max_length=40)),
                ('saddr', models.CharField(max_length=200)),
                ('sprog', models.CharField(max_length=40)),
                ('slocation', models.CharField(max_length=40)),
                ('sgender', models.CharField(max_length=5)),
                ('spic_path', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
