# Generated by Django 2.1.1 on 2019-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=40)),
                ('memail', models.CharField(max_length=40)),
                ('musername', models.CharField(max_length=40)),
                ('mpassword', models.CharField(max_length=40)),
                ('mcontact', models.CharField(max_length=40)),
                ('mpic_path', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
