# Generated by Django 2.1.1 on 2019-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_marketeer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='event_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='evduration',
            new_name='evdur',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='saddr',
            new_name='sadd',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='slocation',
            new_name='scity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='evexpectedfund',
        ),
        migrations.RemoveField(
            model_name='event',
            name='evloc',
        ),
        migrations.AlterField(
            model_name='student',
            name='sprog',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
