# Generated by Django 2.1.1 on 2019-02-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='evlocation',
            field=models.CharField(default='', max_length=40),
        ),
    ]
