# Generated by Django 2.1.1 on 2019-02-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_event_evlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='evtype',
            field=models.CharField(default='education', max_length=40),
        ),
    ]
