# Generated by Django 2.1.1 on 2019-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_event_evtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ev_exfunds',
            field=models.CharField(default='10000', max_length=40),
        ),
    ]
