# Generated by Django 2.1.1 on 2019-02-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_event_ev_exfunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(default='positive', max_length=50),
        ),
    ]
