# Generated by Django 2.1.1 on 2019-02-06 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_comment_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cvdate',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
