# Generated by Django 2.1.1 on 2019-02-06 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_comment_cvdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('cvdate', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('event_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.Event')),
            ],
        ),
    ]
